import React from 'react';

const Blogs = () => {
    return (
        <div>
            <div className="w-2/3 mx-auto">
                <h2 className="text-2xl font-bold mb-4 text-center">Q & A Section</h2>

                <div className="space-y-4">
                    <div className="bg-white shadow-md rounded-lg p-4">
                        <h3 className="text-lg font-semibold mb-2">Question 1: What is an access token and refresh token? How do they work and where should we store them on the client-side?</h3>
                        <p className="text-gray-800">
                            An access token and refresh token are commonly used in authentication and authorization systems. Here s an overview of what they are, how they work, and where they should be stored on the client-side:

                            Access Token:
                            An access token is a credential that represents the authorization granted to a client (such as a user or an application) to access protected resources on a server. It is usually a string of characters that is generated by the server upon successful authentication. The access token is then included in each subsequent request to the server to access protected resources.

                            Refresh Token:
                            A refresh token is a credential that is used to obtain a new access token when the current access token expires. It is typically issued alongside the access token during the authentication process. Unlike the access token, the refresh token is typically long-lived and is used to request a new access token without having to reauthenticate the user.
                        </p>
                    </div>

                    <div className="bg-white shadow-md rounded-lg p-4">
                        <h3 className="text-lg font-semibold mb-2">Question 2: Compare SQL and NoSQL databases?</h3>
                        <p className="text-gray-800">
                            SQL databases are vertically scalable, while NoSQL databases are horizontally scalable. SQL databases are table-based, while NoSQL databases are document, key-value, graph, or wide-column stores. SQL databases are better for multi-row transactions, while NoSQL is better for unstructured data like documents or JSON.
                        </p>
                    </div>
                    <div className="bg-white shadow-md rounded-lg p-4">
                        <h3 className="text-lg font-semibold mb-2">Question 3: What is express js? What is Nest JS</h3>
                        <p className="text-gray-800">
                            NestJS is a framework for developing modern server-side applications in Node. js. It is built on top of Express, a popular server framework for Node. js, and provides a robust set of features for building efficient, scalable, and enterprise-grade applications.
                        </p>
                    </div>
                    <div className="bg-white shadow-md rounded-lg p-4">
                        <h3 className="text-lg font-semibold mb-2">Question 4: What is MongoDB aggregate and how does it work?</h3>
                        <p className="text-gray-800">
                            Aggregation is a way of processing a large number of documents in a collection by means of passing them through different stages. The stages make up what is known as a pipeline. The stages in a pipeline can filter, sort, group, reshape and modify documents that pass through the pipeline.
                        </p>
                    </div>

                    {/* Add more Q&A cards here */}
                </div>
            </div>
        </div>
    );
};

export default Blogs;